# Generated by Django 3.0.4 on 2020-07-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Release_Date', models.DateTimeField()),
                ('Rating', models.FloatField()),
                ('Director', models.CharField(max_length=100)),
                ('Writer', models.CharField(max_length=100)),
                ('Actor', models.CharField(max_length=100)),
                ('Production', models.CharField(max_length=100)),
                ('Summary', models.CharField(max_length=200)),
                ('Language', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('posters', models.ImageField(upload_to='images/')),
                ('Trailer', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
