# Generated by Django 3.0.4 on 2020-07-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Trailer',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
